"""add prompt

Revision ID: e32744a9cd8f
Revises: 0e851bb23603
Create Date: 2025-12-01 15:19:19.135321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e32744a9cd8f'
down_revision: Union[str, None] = '0e851bb23603'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompt',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('title', sa.Text(), nullable=True, comment='标题'),
    sa.Column('image', sa.Text(), nullable=True, comment='图片'),
    sa.Column('source', sa.Text(), nullable=True, comment='来源'),
    sa.Column('prompt_en', sa.Text(), nullable=True, comment='英文Prompt'),
    sa.Column('prompt_zh', sa.Text(), nullable=True, comment='中文Prompt'),
    sa.Column('source_url', sa.Text(), nullable=True, comment='来源链接'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prompt'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prompt')
    # ### end Alembic commands ###
